tasks:
  - init: NG_CLI_ANALYTICS=ci npm install
    command: npm run start

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint@0.36.1
    - dbaeumer.vscode-eslint@2.1.3
    - Angular.ng-template@0.1000.2
    - vscode-icons-team.vscode-icons@10.1.1
    - esbenp.prettier-vscode@5.1.3
    - msjsdiag.debugger-for-chrome@4.12.6
    - oderwat.indent-rainbow@7.4.0
    - CoenraadS.bracket-pair-colorizer-2@0.1.4
    - mrmlnc.vscode-scss@0.9.1
    - johnpapa.Angular2@9.1.2
    - christian-kohler.path-intellisense@2.2.1
    - formulahendry.auto-close-tag@0.5.7
    - Gruntfuggly.todo-tree@0.0.177
    - wayou.vscode-todo-highlight@1.0.4
